export const CREATE_TODO = 'TODOS/CREATE_TODO';

export const DELETE_TODO = 'TODOS/DELETE_TODO';

export const DOWNLOADED_TODOS = 'TODOS/DOWNLOADED_TODOS';

export const CLEAR_COMPLETED_TODOS = 'TODOS/CLEAR_COMPLETED_TODOS';

export const CHANGE_COMPLETED_TODOS = 'TODOS/CHANGE_COMPLETED_TODOS';

export const EDITING_TODO = 'TODO/EDITING_TODO';

export const TOGGLE_COMPLETE = 'TODOS/TOGGLE_COMPLETE';

export const FILTERED_TODOS = 'TODOS/FILTERED_TODOS';